package net.project.ems.mapper;

import com.fasterxml.jackson.databind.ObjectMapper;
import net.project.ems.dto.UserDto;
import net.project.ems.entity.User;
import org.springframework.context.annotation.Bean;
import org.springframework.stereotype.Component;

@Component
public class UserMapper {

    // Convert UserRegistrationDto to User entity
    public User toEntity(UserDto registrationDto) {
        return new User(
                 // The ID will be auto-generated by the database
                registrationDto.getEmail(),
                registrationDto.getPassword()
        );
    }

    // Convert User entity to UserRegistrationDto
    public UserDto toDto(User user) {
        return new UserDto(
                user.getEmail(),
                user.getPassword()
        );
    }


}
